on:
  pull_request:
    paths:
    - '4.18/**'

permissions:
  contents: read

jobs:
  checkpatch:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Run checkpatch review
        uses: webispy/checkpatch-action@master
